# Generated by Django 5.0 on 2024-03-01 22:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lenguaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='lenguajes/')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('urlDocumentation', models.URLField(max_length=2083)),
                ('totalNiveles', models.PositiveIntegerField(default=0)),
                ('estado', models.BooleanField(default=False)),
                ('registro', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(default='predeterminados/user_default.png', upload_to='usuario/')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=False)),
                ('registro', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('explanation', models.TextField()),
                ('totalPreguntas', models.PositiveIntegerField(default=0)),
                ('estado', models.BooleanField(default=False)),
                ('registro', models.DateField(default=django.utils.timezone.now)),
                ('idLenguaje', models.ForeignKey(limit_choices_to={'estado': True}, on_delete=django.db.models.deletion.CASCADE, related_name='nivel_lenguaje', to='api.lenguaje')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPregunta', models.CharField(choices=[('opcion_multiple', 'Pregunta de opción múltiple'), ('verdadero_falso', 'Pregunta de verdadero y falso'), ('respuesta_abierta', 'Pregunta de respuesta abierta')], max_length=20)),
                ('explanation', models.TextField()),
                ('pregunta', models.TextField()),
                ('respuesta', models.JSONField()),
                ('estado', models.BooleanField(default=False)),
                ('registro', models.DateField(default=django.utils.timezone.now)),
                ('idNivel', models.ForeignKey(limit_choices_to={'estado': True}, on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_nivel', to='api.nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progresoLenguaje', models.FloatField(default=0)),
                ('historial', models.JSONField()),
                ('puntos', models.PositiveIntegerField(default=0)),
                ('registro', models.DateField(default=django.utils.timezone.now)),
                ('idLenguaje', models.ForeignKey(limit_choices_to={'estado': True}, on_delete=django.db.models.deletion.CASCADE, to='api.lenguaje')),
                ('idUsuario', models.ForeignKey(limit_choices_to={'estado': True}, on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]
