# Generated by Django 5.0.2 on 2024-03-03 01:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_lenguaje_registro_alter_nivel_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lenguaje',
            name='registro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='registro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='registro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='progreso',
            name='registro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='registro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
