# Generated by Django 5.0 on 2024-03-03 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_lenguaje_registro_alter_nivel_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('registro', models.DateTimeField(auto_now_add=True)),
                ('idUsuario', models.ForeignKey(limit_choices_to={'estado': True}, on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario')),
            ],
        ),
    ]
