# Generated by Django 5.0.3 on 2024-03-07 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usuariotoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariotoken',
            name='idUsuario',
            field=models.ForeignKey(limit_choices_to={'estado': True}, on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
    ]
