# Generated by Django 5.0.3 on 2024-03-09 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_fotousuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FotoUsuario',
        ),
    ]
